In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data = np.array([[30, 400], [32, 500], [35, 540], [40, 600], [50, 800]])
data

array([[ 30, 400],
       [ 32, 500],
       [ 35, 540],
       [ 40, 600],
       [ 50, 800]])

In [28]:
mean_x = np.mean(data, axis=0)
mean_x

array([ 37.4, 568. ])

In [26]:
std_x = np.std(data, axis=0)

array([  7.14422844, 133.02631319])

In [55]:
normalize = (data-mean_x)/std_x
normalize

In [76]:
arr = np.array(pd.read_csv('C:/Users/toduc/OneDrive - National Economics University/Desktop/NEU/Machine Learning/Visualization/Data/Seattle2014.csv'))
rain = np.count_nonzero(arr[:,3])
no_rain = 365 - rain
rain


150

In [91]:
tol_rain = np.sum(arr[:,3])
print(tol_rain)
avg_rain = tol_rain/rain
avg_rain

12328


82.18666666666667

In [84]:
more_than_half = arr[:,3] > (254/2)
days = np.sum(more_than_half)
days

37

In [92]:
dataset = np.array([['Quần thun', 10, 50000], ['Áo gió', 5, 90000], ['Tất', 50, 8000], ['Giày', 1, 200000], ['Mũ', 1, 30000], ['Quần jean', 3, 100000], ['Áo len', 10, 100000]])
dataset


array([['Quần thun', '10', '50000'],
       ['Áo gió', '5', '90000'],
       ['Tất', '50', '8000'],
       ['Giày', '1', '200000'],
       ['Mũ', '1', '30000'],
       ['Quần jean', '3', '100000'],
       ['Áo len', '10', '100000']], dtype='<U9')

In [98]:
tol_items = np.count_nonzero(dataset[:,0])
tol_items

array([False,  True, False,  True, False,  True,  True])

In [99]:
price50 = dataset[:,2].astype(int)
price50 > 50000

price50

IndexError: index -50001 is out of bounds for axis 0 with size 7

In [102]:
price = dataset[:,1].astype(int)
value = dataset[:,2].astype(int)

tol = price * value

tol

print(tol>300000)

[ True  True  True False False False  True]
